/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package done.s.p0101;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author DoanNC
 */
public class TreeForm extends javax.swing.JFrame {

    /**
     * Creates new form TreeForm
     */
    DefaultTreeModel model;
    DefaultMutableTreeNode root;
    DefaultMutableTreeNode selectedNode;

    public TreeForm() {
        initComponents();
        loadTree();
    }

    void loadTree() {
        model = (DefaultTreeModel) treeData.getModel();
        root = (DefaultMutableTreeNode) model.getRoot();
        root.setUserObject("This is root");
        txtAdd.setFocusable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAdd = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeData = new javax.swing.JTree();
        btnRemove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        txtAdd.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtAdd.setText("Add new node here and press enter");
        txtAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAddMouseClicked(evt);
            }
        });
        txtAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAddKeyPressed(evt);
            }
        });

        treeData.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Day la Root");
        treeData.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        treeData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treeDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(treeData);

        btnRemove.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRemove.setText("Select node and click here to remove from the tree");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtAdd)
            .addComponent(jScrollPane1)
            .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemove)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void treeDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treeDataMouseClicked
        // TODO add your handling code here:
        selectedNode = (DefaultMutableTreeNode) treeData.getLastSelectedPathComponent();
    }//GEN-LAST:event_treeDataMouseClicked

    private void txtAddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && selectedNode != null) {
            selectedNode.add(new DefaultMutableTreeNode(txtAdd.getText()));
//            JOptionPane.showMessageDialog(this, "add " + txtAdd.getText() + " to " + selectedNode.getUserObject().toString());
            model.reload(selectedNode);
            lib.tree.expandAllNodes(treeData, root.getIndex(selectedNode), treeData.getRowCount());
            selectedNode = null;
        }
    }//GEN-LAST:event_txtAddKeyPressed

    private void txtAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAddMouseClicked
        // TODO add your handling code here:
        if (txtAdd.getText().equalsIgnoreCase("Add new node here and press enter")) {
            txtAdd.setText("");
            txtAdd.setFocusable(true);
            txtAdd.requestFocus();
        }
    }//GEN-LAST:event_txtAddMouseClicked

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        if (selectedNode == root) {
            JOptionPane.showMessageDialog(this, "This must have at least one node. So you can not remove root");
            if (JOptionPane.showConfirmDialog(this, "Do you want to change its data?", "Change root", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                root.setUserObject(JOptionPane.showInputDialog("Give me a string"));
                model.reload();
            }
        } else if (selectedNode != null) {
            model.removeNodeFromParent(selectedNode);
            selectedNode = null;
            model.reload();
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TreeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TreeForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemove;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree treeData;
    private javax.swing.JTextField txtAdd;
    // End of variables declaration//GEN-END:variables
}
