/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datnp.ui;

import datnp.daos.ItemDAO;
import datnp.daos.SupplierDAO;
import datnp.dtos.ItemDTO;
import datnp.dtos.SupplierDTO;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import valid.validation;

/**
 *
 * @author dnn84
 */
public class Main extends javax.swing.JFrame {

    SupplierDAO supDAO = new SupplierDAO();
    List<SupplierDTO> supList = supDAO.getAllSup();
    DefaultTableModel Smodel = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    ItemDAO itemDAO = new ItemDAO();
    DefaultTableModel Imodel = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    List<ItemDTO> itemList = itemDAO.getAllItem();
    DefaultComboBoxModel combobox = new DefaultComboBoxModel();
    validation vl = new validation();

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();

        // show sup table
        jTableSup.setModel(Smodel);
        Smodel.addColumn("Code");
        Smodel.addColumn("Name");
        Smodel.addColumn("Address");
        showSupTable();
        // show item table
        jTableItem.setModel(Imodel);
        Imodel.addColumn("Code");
        Imodel.addColumn("Name");
        Imodel.addColumn("Supplier");
        Imodel.addColumn("Unit");
        Imodel.addColumn("Price");
        Imodel.addColumn("Supply");
        showItemTable();
        //add combobox
        addComboBox();
        jButtonSaveSup.setEnabled(false);
        jButtonDeleteSup.setEnabled(false);
        jButtonSaveItem.setEnabled(false);
        jButtonDeleteItem.setEnabled(false);
    }

    public void addComboBox() {
        combobox.removeAllElements();
        for (SupplierDTO sup : supList) {
            combobox.addElement(sup.toString());
        }
        jComboBoxSup.setModel(combobox);
    }

    public void showItemTable() {
        itemList = itemDAO.getAllItem();
        Imodel.setRowCount(0);
        for (ItemDTO Item : itemList) {
            SupplierDTO sup = supDAO.getSupByCode(Item.getSupCode());
            Imodel.addRow(new Object[]{Item.getItemCode(), Item.getItemName(), sup.toString(), Item.getUnit(), Item.getPrice(), Item.isSupplying()});
        }
    }

    public void clearItemForm() {
        jTextFieldCodeItem.setText("");
        jTextFieldCodeItem.setEnabled(true);
        jTextFieldNameItem.setText("");
        jTextFieldPrice.setText("");
        jTextFieldUnit.setText("");
//        checkboxSupplying.setState(false);
    }

    public void showSupTable() {
        supList = supDAO.getAllSup();
        Smodel.setRowCount(0);
        for (SupplierDTO Supplier : supList) {
            Smodel.addRow(new Object[]{Supplier.getSupCode(), Supplier.getSupName(), Supplier.getAddress()});
        }
    }

    public void clearSupForm() {
        jTextFieldCodeSup.setText("");
        jTextFieldCodeSup.setEnabled(true);
        jTextFieldNameSup.setText("");
        jTextFieldAddressSup.setText("");
//        checkboxCollaborating.setState(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSup = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNameSup = new javax.swing.JTextField();
        jTextFieldAddressSup = new javax.swing.JTextField();
        jTextFieldCodeSup = new javax.swing.JTextField();
        checkboxCollaborating = new java.awt.Checkbox();
        jButtonAddSup = new javax.swing.JButton();
        jButtonDeleteSup = new javax.swing.JButton();
        jButtonSaveSup = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldNameItem = new javax.swing.JTextField();
        jTextFieldUnit = new javax.swing.JTextField();
        jTextFieldPrice = new javax.swing.JTextField();
        jTextFieldCodeItem = new javax.swing.JTextField();
        checkboxSupplying = new java.awt.Checkbox();
        jComboBoxSup = new javax.swing.JComboBox<>();
        jButtonAddItem = new javax.swing.JButton();
        jButtonDeleteItem = new javax.swing.JButton();
        jButtonSaveItem = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableItem = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jTableSup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableSup.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableSup.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableSup.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableSup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSupMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableSup);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Code :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Name :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Collaborating :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Address :");

        jButtonAddSup.setText("ADD");
        jButtonAddSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddSupActionPerformed(evt);
            }
        });

        jButtonDeleteSup.setText("DELETE");
        jButtonDeleteSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteSupActionPerformed(evt);
            }
        });

        jButtonSaveSup.setText("SAVE");
        jButtonSaveSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveSupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldNameSup, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldAddressSup, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldCodeSup, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(checkboxCollaborating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAddSup, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonSaveSup, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDeleteSup, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jTextFieldCodeSup))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNameSup, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAddressSup, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkboxCollaborating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddSup, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeleteSup, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSaveSup, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Supplier", jPanel1);

        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Item Code :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Suppiler :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Item Name :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Price :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Supplying :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Unit :");

        jButtonAddItem.setText("ADD");
        jButtonAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddItemActionPerformed(evt);
            }
        });

        jButtonDeleteItem.setText("DELETE");
        jButtonDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteItemActionPerformed(evt);
            }
        });

        jButtonSaveItem.setText("SAVE");
        jButtonSaveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveItemActionPerformed(evt);
            }
        });

        jTableItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableItem.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableItemMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableItem);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCodeItem, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jComboBoxSup, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextFieldNameItem, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(checkboxSupplying, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jButtonAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSaveItem, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonDeleteItem, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(16, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCodeItem, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNameItem, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jComboBoxSup, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(checkboxSupplying, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeleteItem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSaveItem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(193, Short.MAX_VALUE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Item", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddSupActionPerformed
        // TODO add your handling code here:
        SupplierDTO sup = new SupplierDTO();
        sup.setSupCode(jTextFieldCodeSup.getText());
        sup.setSupName(jTextFieldNameSup.getText());
        sup.setAddress(jTextFieldAddressSup.getText());
        sup.setCollaborating(checkboxCollaborating.getState());
        if (vl.checkSup(sup, true, supList)) {
            supDAO.addSup(sup);
            JOptionPane.showMessageDialog(null, "Add success");
            showSupTable();
            clearSupForm();
            addComboBox();
            jButtonSaveSup.setEnabled(false);
            jButtonDeleteSup.setEnabled(false);
            jButtonAddSup.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "Add failed");
        }

    }//GEN-LAST:event_jButtonAddSupActionPerformed

    private void jButtonDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteItemActionPerformed
        // TODO add your handling code here:
        String code = jTextFieldCodeItem.getText();
        if (itemDAO.deleteItem(code)) {
            JOptionPane.showMessageDialog(null, "Delete success");
        } else {
            JOptionPane.showMessageDialog(null, "Delete faild");
        };
        showItemTable();
        clearItemForm();
        jButtonSaveItem.setEnabled(false);
        jButtonDeleteItem.setEnabled(false);
        jButtonAddItem.setEnabled(true);
    }//GEN-LAST:event_jButtonDeleteItemActionPerformed

    private void jTableSupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSupMouseClicked
        // TODO add your handling code here:
        int index = jTableSup.getSelectedRow();
        jTextFieldCodeSup.setText((String) jTableSup.getValueAt(index, 0));
        jTextFieldCodeSup.setEnabled(false);
        jTextFieldNameSup.setText((String) jTableSup.getValueAt(index, 1));
        jTextFieldAddressSup.setText((String) jTableSup.getValueAt(index, 2));
        checkboxCollaborating.setState(supList.get(index).isCollaborating());
        jButtonSaveSup.setEnabled(true);
        jButtonDeleteSup.setEnabled(true);
        jButtonAddSup.setEnabled(false);
    }//GEN-LAST:event_jTableSupMouseClicked

    private void jButtonDeleteSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteSupActionPerformed
        // TODO add your handling code here:
        String code = jTextFieldCodeSup.getText();
        List<ItemDTO> list = new ItemDAO().getAllItemBySupCode(code);
        if(list.isEmpty()){
            if(supDAO.deleteSup(code)) {JOptionPane.showMessageDialog(null, "Delete success");}
            else{JOptionPane.showMessageDialog(null, "Delete faild");}
        }else{
            JOptionPane.showMessageDialog(null, "Supplier have constraint");
        }
        
        showSupTable();
        clearSupForm();
        addComboBox();
        jButtonSaveSup.setEnabled(false);
        jButtonDeleteSup.setEnabled(false);
        jButtonAddSup.setEnabled(true);
    }//GEN-LAST:event_jButtonDeleteSupActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        clearSupForm();
        jButtonSaveSup.setEnabled(false);
        jButtonDeleteSup.setEnabled(false);
        jButtonAddSup.setEnabled(true);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jButtonSaveSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveSupActionPerformed
        // TODO add your handling code here:
        String supCode = jTextFieldCodeSup.getText();
        String supName = jTextFieldNameSup.getText();
        String supAddress = jTextFieldAddressSup.getText();
        boolean collaborating = checkboxCollaborating.getState();
        SupplierDTO dto = new SupplierDTO(supCode, supName, supAddress, collaborating);
        if (vl.checkSup(dto, false, supList)) {
            if (supDAO.updateSup(dto)) {
                JOptionPane.showMessageDialog(null, "Success");
                clearSupForm();
                addComboBox();
                showSupTable();
                jButtonAddSup.setEnabled(true);
                jButtonSaveSup.setEnabled(false);
                jButtonDeleteSup.setEnabled(false);
            }else{
                JOptionPane.showConfirmDialog(null, "faild");
            }
        } else {
            JOptionPane.showConfirmDialog(null, "faild");
        }

    }//GEN-LAST:event_jButtonSaveSupActionPerformed

    private void jButtonAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddItemActionPerformed
        // TODO add your handling code here:
        ItemDTO item = new ItemDTO();
        String code = jTextFieldCodeItem.getText();
        String name = jTextFieldNameItem.getText();
        String supCode = "";
        for (SupplierDTO Supplier : supList) {
            if (Supplier.toString().equals(jComboBoxSup.getSelectedItem().toString())) {
                supCode = Supplier.getSupCode();
            }
        }
        String unit = jTextFieldUnit.getText();
        String price = jTextFieldPrice.getText();
        boolean supplying = checkboxSupplying.getState();
        item = vl.checkItem(item, true, itemList, code, name, supCode, unit, price, supplying);
        if (item != null) {
            itemDAO.addItem(item);
            JOptionPane.showMessageDialog(null, "Add Success");
            showItemTable();
            clearItemForm();
            jButtonSaveItem.setEnabled(false);
            jButtonDeleteItem.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "Add failed");
        };
    }//GEN-LAST:event_jButtonAddItemActionPerformed

    private void jTableItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableItemMouseClicked
        // TODO add your handling code here:
        int index = jTableItem.getSelectedRow();
        jTextFieldCodeItem.setText((String) jTableItem.getValueAt(index, 0));
        jTextFieldCodeItem.setEnabled(false);
        jTextFieldNameItem.setText((String) jTableItem.getValueAt(index, 1));
        jComboBoxSup.setSelectedItem(jTableItem.getValueAt(index, 2));
        jTextFieldUnit.setText((String) jTableItem.getValueAt(index, 3));
        jTextFieldPrice.setText(String.valueOf(jTableItem.getValueAt(index, 4)));
        checkboxSupplying.setState((boolean) jTableItem.getValueAt(index, 5));
        jButtonSaveItem.setEnabled(true);
        jButtonDeleteItem.setEnabled(true);
        jButtonAddItem.setEnabled(false);
    }//GEN-LAST:event_jTableItemMouseClicked

    private void jButtonSaveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveItemActionPerformed
        // TODO add your handling code here:
        ItemDTO item = new ItemDTO();
        String code = jTextFieldCodeItem.getText();
        String name = jTextFieldNameItem.getText();
        String supCode = "";
        for (SupplierDTO Supplier : supList) {
            if (Supplier.toString().equals(jComboBoxSup.getSelectedItem().toString())) {
                supCode = Supplier.getSupCode();
            }
        }
        String unit = jTextFieldUnit.getText();
        String price = jTextFieldPrice.getText();
        boolean supplying = checkboxSupplying.getState();
        item = vl.checkItem(item, false, itemList, code, name, supCode, unit, price, supplying);
        if (item != null) {
            itemDAO.saveItem(item);
            JOptionPane.showMessageDialog(null, "Edit Success");
            showItemTable();
            clearItemForm();
            jButtonSaveItem.setEnabled(false);
            jButtonDeleteItem.setEnabled(false);
            jButtonAddItem.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "Edit failed");
            
        };
    }//GEN-LAST:event_jButtonSaveItemActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        clearItemForm();
        jButtonSaveItem.setEnabled(false);
        jButtonDeleteItem.setEnabled(false);
        jButtonAddItem.setEnabled(true);
    }//GEN-LAST:event_jPanel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox checkboxCollaborating;
    private java.awt.Checkbox checkboxSupplying;
    private javax.swing.JButton jButtonAddItem;
    private javax.swing.JButton jButtonAddSup;
    private javax.swing.JButton jButtonDeleteItem;
    private javax.swing.JButton jButtonDeleteSup;
    private javax.swing.JButton jButtonSaveItem;
    private javax.swing.JButton jButtonSaveSup;
    private javax.swing.JComboBox<String> jComboBoxSup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableItem;
    private javax.swing.JTable jTableSup;
    private javax.swing.JTextField jTextFieldAddressSup;
    private javax.swing.JTextField jTextFieldCodeItem;
    private javax.swing.JTextField jTextFieldCodeSup;
    private javax.swing.JTextField jTextFieldNameItem;
    private javax.swing.JTextField jTextFieldNameSup;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldUnit;
    // End of variables declaration//GEN-END:variables
}
