/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package j2.s.p0104;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kim ngân
 */
public class RowInTable extends javax.swing.JFrame {

    DefaultTableModel df = new DefaultTableModel();
    int tableRows;

    /**
     * Creates new form RowInTable
     */
    public RowInTable() throws Exception {
        initComponents();
        setLocationRelativeTo(null);
        dataTable();
        jTable1.setEnabled(false);
        jTable1.setRowSelectionInterval(0, 0);
        
    }

    public void dataTable() throws Exception {
        Object[] titler = {"StockId", "StockName", "Address", "DateAvailable", "Note"};
        Object[][] data = {
                {"1", "Stock one", "Ho Chi Minh", "2019-01-26", ""},
                {"2", "Stock two", "Dong Thap", "2019-11-23", ""},
                {"3", "Stock three", "Long An", "2019-12-24", ""},
                {"4", "Stock four", "Binh Dinh", "2019-01-01", ""},
                {"5", "Stock five", "Da Nang", "2019-02-01", ""}
            
        };
        tableRows = data.length;
        df.setDataVector(data, titler);
        jTable1.setModel(df);
    }
    public void moveRow(int index ){
        int[] rows = jTable1.getSelectedRows();
        int des = rows[0] + index;
        if(des < 0 || des >= tableRows){
            return;
        }
        jTable1.setRowSelectionInterval(rows[0] + index, rows[0] + index);
       
    }

    /** 
    }
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        firstRow = new javax.swing.JButton();
        prevRow = new javax.swing.JButton();
        nextRow = new javax.swing.JButton();
        lastRow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        firstRow.setText("Move First");
        firstRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstRowActionPerformed(evt);
            }
        });

        prevRow.setText("Move Previous");
        prevRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevRowActionPerformed(evt);
            }
        });

        nextRow.setText("Move Next");
        nextRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextRowActionPerformed(evt);
            }
        });

        lastRow.setText("Move Last");
        lastRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastRowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(firstRow)
                .addGap(41, 41, 41)
                .addComponent(prevRow)
                .addGap(30, 30, 30)
                .addComponent(nextRow)
                .addGap(32, 32, 32)
                .addComponent(lastRow)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(317, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstRow)
                    .addComponent(prevRow)
                    .addComponent(nextRow)
                    .addComponent(lastRow))
                .addGap(50, 50, 50))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(103, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstRowActionPerformed
        // TODO add your handling code here:
        jTable1.setRowSelectionInterval(0, 0);
    }//GEN-LAST:event_firstRowActionPerformed

    private void prevRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevRowActionPerformed
        // TODO add your handling code here:
        moveRow(-1);
    }//GEN-LAST:event_prevRowActionPerformed

    private void nextRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextRowActionPerformed
        // TODO add your handling code here:
        moveRow(1);
    }//GEN-LAST:event_nextRowActionPerformed

    private void lastRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastRowActionPerformed
        // TODO add your handling code here:
        jTable1.setRowSelectionInterval(tableRows - 1, tableRows - 1);
    }//GEN-LAST:event_lastRowActionPerformed

    /**
       
    }
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html*/ 
     //public void dataTable() throws Exception {
//        Object[] titler = {"StockId", "StockName", "Address", "DateAvailable", "Note"};
//        Object[][] data = {
//                {"1", "Stock one", "Ho Chi Minh", "2019-01-26", ""},
//                {"2", "Stock two", "Dong Thap", "2019-11-23", ""},
//                {"3", "Stock three", "Long An", "2019-12-24", ""},
//                {"4", "Stock four", "Binh Dinh", "2019-01-01", ""},
//                {"5", "Stock five", "Da Nang", "2019-02-01", ""}
//            
//        };
//        tableRows = data.length;
//        df.setDataVector(data, titler);
//        jTable1.setModel(df);
//          public void moveRow(int index ){
//        int[] rows = jTable1.getSelectedRows();
//        int des = rows[0] + index;
//        if(des < 0 || des >= tableRows){
//            return;
//        }
//        jTable1.setRowSelectionInterval(rows[0] + index, rows[0] + index);
//       
//    }
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RowInTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RowInTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RowInTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RowInTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new RowInTable().setVisible(true);
                } catch (Exception e) {
                    Logger.getLogger(RowInTable.class.getName()).log(Level.SEVERE,null,e);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton firstRow;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton lastRow;
    private javax.swing.JButton nextRow;
    private javax.swing.JButton prevRow;
    // End of variables declaration//GEN-END:variables
}
