USE [master]
GO

/****** Object:  Database [J2.L.P0001]    Script Date: 12/12/2020 2:24:32 PM ******/
CREATE DATABASE [J2.L.P0001]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'J2.L.P0001', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\J2.L.P0001.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'J2.L.P0001_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\J2.L.P0001_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [J2.L.P0001] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [J2.L.P0001].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [J2.L.P0001] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [J2.L.P0001] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [J2.L.P0001] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [J2.L.P0001] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [J2.L.P0001] SET ARITHABORT OFF 
GO

ALTER DATABASE [J2.L.P0001] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [J2.L.P0001] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [J2.L.P0001] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [J2.L.P0001] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [J2.L.P0001] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [J2.L.P0001] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [J2.L.P0001] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [J2.L.P0001] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [J2.L.P0001] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [J2.L.P0001] SET  DISABLE_BROKER 
GO

ALTER DATABASE [J2.L.P0001] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [J2.L.P0001] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [J2.L.P0001] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [J2.L.P0001] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [J2.L.P0001] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [J2.L.P0001] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [J2.L.P0001] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [J2.L.P0001] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [J2.L.P0001] SET  MULTI_USER 
GO

ALTER DATABASE [J2.L.P0001] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [J2.L.P0001] SET DB_CHAINING OFF 
GO

ALTER DATABASE [J2.L.P0001] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [J2.L.P0001] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [J2.L.P0001] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [J2.L.P0001] SET  READ_WRITE 
GO


