/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package j2.l.p0022;

import java.awt.Color;
import java.awt.Container;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author DoanNC
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    Calculus cal;
    boolean isDecimal = false;
    boolean isNewNum = true;
    int maxLength = 9;
    double buffer = 0;
    Color hover = new Color(153, 255, 153);
    Color lightRed = new Color(255, 153, 153);
    Color warmRed = new Color(255, 102, 102);
    Color originColor;
    String operation = "none";

    public Calculator() {
        initComponents();
        cal = new Calculus();
        txtResult.setEditable(false);
        txtResult.setFocusable(false);
        originColor = btnMR.getBackground();
        new Thread(() -> {
            try {
                while (true) {
                    if (txtResult.getText().equals("0")) {
                        btnClear.setText("CE");
                        btnClear.setBackground(warmRed);
                    } else {
                        btnClear.setText("C");
                        btnClear.setBackground(lightRed);
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Please click slower");
            }
        }).start();
        removeFocusable();
        createKeyRecorder((Container) this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtResult = new javax.swing.JTextField();
        btnMC = new javax.swing.JButton();
        btnMR = new javax.swing.JButton();
        btnMadd = new javax.swing.JButton();
        btnMsub = new javax.swing.JButton();
        btnSqrt = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btnDivTo100 = new javax.swing.JButton();
        btnSub = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btnResult = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnMul = new javax.swing.JButton();
        btnDivBy1 = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnOpposite = new javax.swing.JButton();
        btnDot = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setResizable(false);

        txtResult.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        txtResult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtResult.setText("0");
        txtResult.setPreferredSize(new java.awt.Dimension(324, 50));

        btnMC.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnMC.setText("MC");
        btnMC.setMaximumSize(new java.awt.Dimension(60, 50));
        btnMC.setMinimumSize(new java.awt.Dimension(60, 50));
        btnMC.setPreferredSize(new java.awt.Dimension(60, 50));
        btnMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMCActionPerformed(evt);
            }
        });

        btnMR.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnMR.setText("MR");
        btnMR.setMaximumSize(new java.awt.Dimension(60, 50));
        btnMR.setMinimumSize(new java.awt.Dimension(60, 50));
        btnMR.setPreferredSize(new java.awt.Dimension(60, 50));
        btnMR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMRActionPerformed(evt);
            }
        });

        btnMadd.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnMadd.setText("M+");
        btnMadd.setMaximumSize(new java.awt.Dimension(60, 50));
        btnMadd.setMinimumSize(new java.awt.Dimension(60, 50));
        btnMadd.setPreferredSize(new java.awt.Dimension(60, 50));
        btnMadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaddActionPerformed(evt);
            }
        });

        btnMsub.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnMsub.setText("M-");
        btnMsub.setMaximumSize(new java.awt.Dimension(60, 50));
        btnMsub.setMinimumSize(new java.awt.Dimension(60, 50));
        btnMsub.setPreferredSize(new java.awt.Dimension(60, 50));
        btnMsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMsubActionPerformed(evt);
            }
        });

        btnSqrt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnSqrt.setText("√");
        btnSqrt.setMaximumSize(new java.awt.Dimension(60, 50));
        btnSqrt.setMinimumSize(new java.awt.Dimension(60, 50));
        btnSqrt.setPreferredSize(new java.awt.Dimension(60, 50));
        btnSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSqrtActionPerformed(evt);
            }
        });

        btnDiv.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnDiv.setText("÷");
        btnDiv.setMaximumSize(new java.awt.Dimension(60, 50));
        btnDiv.setMinimumSize(new java.awt.Dimension(60, 50));
        btnDiv.setPreferredSize(new java.awt.Dimension(60, 50));
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });

        btn9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn9.setText("9");
        btn9.setMaximumSize(new java.awt.Dimension(60, 50));
        btn9.setMinimumSize(new java.awt.Dimension(60, 50));
        btn9.setPreferredSize(new java.awt.Dimension(60, 50));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn8.setText("8");
        btn8.setMaximumSize(new java.awt.Dimension(60, 50));
        btn8.setMinimumSize(new java.awt.Dimension(60, 50));
        btn8.setPreferredSize(new java.awt.Dimension(60, 50));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn7.setText("7");
        btn7.setMaximumSize(new java.awt.Dimension(60, 50));
        btn7.setMinimumSize(new java.awt.Dimension(60, 50));
        btn7.setPreferredSize(new java.awt.Dimension(60, 50));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btnDivTo100.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnDivTo100.setText("%");
        btnDivTo100.setMaximumSize(new java.awt.Dimension(60, 50));
        btnDivTo100.setMinimumSize(new java.awt.Dimension(60, 50));
        btnDivTo100.setPreferredSize(new java.awt.Dimension(60, 50));
        btnDivTo100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivTo100ActionPerformed(evt);
            }
        });

        btnSub.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnSub.setText("-");
        btnSub.setMaximumSize(new java.awt.Dimension(60, 50));
        btnSub.setMinimumSize(new java.awt.Dimension(60, 50));
        btnSub.setPreferredSize(new java.awt.Dimension(60, 50));
        btnSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubActionPerformed(evt);
            }
        });

        btn3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn3.setText("3");
        btn3.setMaximumSize(new java.awt.Dimension(60, 50));
        btn3.setMinimumSize(new java.awt.Dimension(60, 50));
        btn3.setPreferredSize(new java.awt.Dimension(60, 50));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn2.setText("2");
        btn2.setMaximumSize(new java.awt.Dimension(60, 50));
        btn2.setMinimumSize(new java.awt.Dimension(60, 50));
        btn2.setPreferredSize(new java.awt.Dimension(60, 50));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn1.setText("1");
        btn1.setMaximumSize(new java.awt.Dimension(60, 50));
        btn1.setMinimumSize(new java.awt.Dimension(60, 50));
        btn1.setPreferredSize(new java.awt.Dimension(60, 50));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btnResult.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnResult.setText("=");
        btnResult.setMaximumSize(new java.awt.Dimension(60, 50));
        btnResult.setMinimumSize(new java.awt.Dimension(60, 50));
        btnResult.setPreferredSize(new java.awt.Dimension(60, 50));
        btnResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultActionPerformed(evt);
            }
        });

        btn4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn4.setText("4");
        btn4.setMaximumSize(new java.awt.Dimension(60, 50));
        btn4.setMinimumSize(new java.awt.Dimension(60, 50));
        btn4.setPreferredSize(new java.awt.Dimension(60, 50));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn5.setText("5");
        btn5.setMaximumSize(new java.awt.Dimension(60, 50));
        btn5.setMinimumSize(new java.awt.Dimension(60, 50));
        btn5.setPreferredSize(new java.awt.Dimension(60, 50));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn6.setText("6");
        btn6.setMaximumSize(new java.awt.Dimension(60, 50));
        btn6.setMinimumSize(new java.awt.Dimension(60, 50));
        btn6.setPreferredSize(new java.awt.Dimension(60, 50));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btnMul.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnMul.setText("x");
        btnMul.setMaximumSize(new java.awt.Dimension(60, 50));
        btnMul.setMinimumSize(new java.awt.Dimension(60, 50));
        btnMul.setPreferredSize(new java.awt.Dimension(60, 50));
        btnMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulActionPerformed(evt);
            }
        });

        btnDivBy1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnDivBy1.setText("1/x");
        btnDivBy1.setMaximumSize(new java.awt.Dimension(60, 50));
        btnDivBy1.setMinimumSize(new java.awt.Dimension(60, 50));
        btnDivBy1.setPreferredSize(new java.awt.Dimension(60, 50));
        btnDivBy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivBy1ActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnAdd.setText("+");
        btnAdd.setMaximumSize(new java.awt.Dimension(60, 50));
        btnAdd.setMinimumSize(new java.awt.Dimension(60, 50));
        btnAdd.setPreferredSize(new java.awt.Dimension(60, 50));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnOpposite.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnOpposite.setText("+\\-");
        btnOpposite.setMaximumSize(new java.awt.Dimension(60, 50));
        btnOpposite.setMinimumSize(new java.awt.Dimension(60, 50));
        btnOpposite.setPreferredSize(new java.awt.Dimension(60, 50));
        btnOpposite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOppositeActionPerformed(evt);
            }
        });

        btnDot.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnDot.setText(".");
        btnDot.setMaximumSize(new java.awt.Dimension(60, 50));
        btnDot.setMinimumSize(new java.awt.Dimension(60, 50));
        btnDot.setPreferredSize(new java.awt.Dimension(60, 50));
        btnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDotActionPerformed(evt);
            }
        });

        btn0.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn0.setText("0");
        btn0.setMaximumSize(new java.awt.Dimension(60, 50));
        btn0.setMinimumSize(new java.awt.Dimension(60, 50));
        btn0.setPreferredSize(new java.awt.Dimension(60, 50));
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnClear.setText("C");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOpposite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDivTo100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDivBy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMsub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMsub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnOpposite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDivTo100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDivBy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void removeFocusable() {
        btnMC.setFocusable(false);
        btnMR.setFocusable(false);
        btnMadd.setFocusable(false);
        btnMsub.setFocusable(false);
        btnClear.setFocusable(false);
        btn0.setFocusable(false);
        btn1.setFocusable(false);
        btn2.setFocusable(false);
        btn3.setFocusable(false);
        btn4.setFocusable(false);
        btn5.setFocusable(false);
        btn6.setFocusable(false);
        btn7.setFocusable(false);
        btn8.setFocusable(false);
        btn9.setFocusable(false);
        btnDiv.setFocusable(false);
        btnDivBy1.setFocusable(false);
        btnDivTo100.setFocusable(false);
        btnDot.setFocusable(false);
        btnMul.setFocusable(false);
        btnAdd.setFocusable(false);
        btnSub.setFocusable(false);
        btnSqrt.setFocusable(false);
        btnOpposite.setFocusable(false);
        btnResult.setFocusable(false);
    }

    private void createKeyRecorder(Container x) {
        x.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                super.keyPressed(e);
                switch (e.getKeyCode()) {
                    case KeyEvent.VK_0:
                    case KeyEvent.VK_NUMPAD0:
                        btn0ActionPerformed(null);
                        break;
                    case KeyEvent.VK_1:
                    case KeyEvent.VK_NUMPAD1:
                        btn1ActionPerformed(null);
                        break;
                    case KeyEvent.VK_2:
                    case KeyEvent.VK_NUMPAD2:
                        btn2ActionPerformed(null);
                        break;
                    case KeyEvent.VK_3:
                    case KeyEvent.VK_NUMPAD3:
                        btn3ActionPerformed(null);
                        break;
                    case KeyEvent.VK_4:
                    case KeyEvent.VK_NUMPAD4:
                        btn4ActionPerformed(null);
                        break;
                    case KeyEvent.VK_5:
                    case KeyEvent.VK_NUMPAD5:
                        btn5ActionPerformed(null);
                        break;
                    case KeyEvent.VK_6:
                    case KeyEvent.VK_NUMPAD6:
                        btn6ActionPerformed(null);
                        break;
                    case KeyEvent.VK_7:
                    case KeyEvent.VK_NUMPAD7:
                        btn7ActionPerformed(null);
                        break;
                    case KeyEvent.VK_8:
                    case KeyEvent.VK_NUMPAD8:
                        btn8ActionPerformed(null);
                        break;
                    case KeyEvent.VK_9:
                    case KeyEvent.VK_NUMPAD9:
                        btn9ActionPerformed(null);
                        break;
                    case KeyEvent.VK_ENTER:
                        btnResultActionPerformed(null);
                        break;
                    case KeyEvent.VK_SUBTRACT:
                        btnSubActionPerformed(null);
                        break;
                    case KeyEvent.VK_MULTIPLY:
                        btnMulActionPerformed(null);
                        break;
                    case KeyEvent.VK_ADD:
                        btnAddActionPerformed(null);
                        break;
                    case KeyEvent.VK_DIVIDE:
                        btnDivActionPerformed(null);
                        break;
                    case KeyEvent.VK_DELETE:
                    case KeyEvent.VK_BACK_SPACE:
                        btnClearActionPerformed(null);
                        break;
                    case 110:
                        btnDotActionPerformed(null);
                        break;
                    default:
                        break;
                }
            }
        });
    }

    private void setNum(int num) {
        if (isNewNum) {
            txtResult.setText("0");
            isDecimal = false;
            isNewNum = false;
        }
        String tmp = txtResult.getText();
        if (tmp.equals("0")) {
            if (num != 0) {
                txtResult.setText(num + "");
            } else {
                txtResult.setText("0");
            }
        } else {
            if (tmp.length() < maxLength) {
                txtResult.setText(tmp + num);
            }
        }
    }

    private void btnMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMCActionPerformed
        // TODO add your handling code here:
        cal.MC();
        btnMR.setBackground(originColor);
    }//GEN-LAST:event_btnMCActionPerformed

    private void btnMRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMRActionPerformed
        // TODO add your handling code here:
        if (cal.MR() % 1 == 0) {
            txtResult.setText((int) cal.MR() + "");
        } else {
            txtResult.setText(cal.MR() + "");
            isDecimal = true;
        }
        isNewNum = true;
    }//GEN-LAST:event_btnMRActionPerformed

    private void btnMaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaddActionPerformed
        // TODO add your handling code here:
        cal.MAdd(Double.parseDouble(txtResult.getText()));
        isNewNum = true;
        btnMR.setBackground(hover);
    }//GEN-LAST:event_btnMaddActionPerformed

    private void btnMsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMsubActionPerformed
        // TODO add your handling code here:
        cal.MSub(Double.parseDouble(txtResult.getText()));
        isNewNum = true;
        btnMR.setBackground(hover);
    }//GEN-LAST:event_btnMsubActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        setNum(7);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        setNum(8);
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        setNum(9);
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        setNum(4);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        setNum(5);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        setNum(6);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        setNum(1);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        setNum(2);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        setNum(3);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        setNum(0);
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDotActionPerformed
        // TODO add your handling code here:
        if (txtResult.getText().length() < maxLength) {
            if (isNewNum) {
                txtResult.setText("0");
                isNewNum = false;
                isDecimal = false;
            }
            if (!isDecimal) {
                txtResult.setText(txtResult.getText() + ".");
                maxLength += 1;
                isDecimal = true;
            }
        }
    }//GEN-LAST:event_btnDotActionPerformed

    private void btnSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSqrtActionPerformed
        // TODO add your handling code here:
        double tmp = Double.parseDouble(txtResult.getText());
        if (cal.sqrt(tmp) % 1 == 0) {
            txtResult.setText((int) cal.sqrt(tmp) + "");
        } else {
            DecimalFormat df = new DecimalFormat(getDF(cal.sqrt(tmp)));
            txtResult.setText(df.format(cal.sqrt(tmp)));
            isDecimal = true;
        }
        isNewNum = true;
    }//GEN-LAST:event_btnSqrtActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        if (btnClear.getText().equalsIgnoreCase("CE")) {
            buffer = 0;
            operation = null;
            defaultOperationBtnColor();
        }
        txtResult.setText("0");
        maxLength = 9;
        isNewNum = true;
        isDecimal = false;
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnOppositeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOppositeActionPerformed
        // TODO add your handling code here:
        double tmp = cal.opposite(Double.parseDouble(txtResult.getText()));
        if (tmp < 0) {
            maxLength += 1;
        } else {
            maxLength -= 1;
        }
        if (tmp % 1 == 0) {
            txtResult.setText((int) tmp + "");
            isDecimal = false;
        } else {
            txtResult.setText(tmp + "");
            isDecimal = true;
        }
    }//GEN-LAST:event_btnOppositeActionPerformed

    void setTextDouble(double num) {

    }
    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        // TODO add your handling code here:
        if (buffer != 0) {
            btnResultActionPerformed(null);
        }
        operation = "div";
        buffer = Double.parseDouble(txtResult.getText());
        isNewNum = true;
        isDecimal = false;
        btnDiv.setBackground(hover);
    }//GEN-LAST:event_btnDivActionPerformed

    String getDF(double num) {
        String result = "";
        int val = (int) num / 1;
        String len = val + "";
        if (len.length() < maxLength - 1) { //for a dot
            for (int i = 0; i < len.length(); i++) {
                result += "#";
            }
            result += ".";
            String tmp = result;
            for (int i = tmp.length(); i < maxLength; i++) {
                result += "#";
            }
        }
        return result;
    }
    private void btnResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultActionPerformed
        // TODO add your handling code here:
        double num = Double.parseDouble(txtResult.getText());
        if (operation == null) {
            operation = "none";
        }
        switch (operation) {
            case "div":
                if (num == 0) {
                    txtResult.setText("Error");
                } else if (cal.divide(buffer, num) % 1 == 0) {
                    txtResult.setText((int) cal.divide(buffer, num) + "");
                    isDecimal = false;
                } else {
                    DecimalFormat df = new DecimalFormat(getDF(cal.divide(buffer, num)));
                    txtResult.setText(df.format(cal.divide(buffer, num)));
                    isDecimal = true;
                }
                break;
            case "mul":
                if (cal.multiply(buffer, num) % 1 == 0) {
                    txtResult.setText((int) cal.multiply(buffer, num) + "");
                    isDecimal = false;
                } else {
                    txtResult.setText(cal.multiply(buffer, num) + "");
                    isDecimal = true;
                }
                break;
            case "add":
                if (cal.add(buffer, num) % 1 == 0) {
                    txtResult.setText((int) cal.add(buffer, num) + "");
                    isDecimal = false;
                } else {
                    txtResult.setText(cal.add(buffer, num) + "");
                    isDecimal = true;
                }
                break;
            case "sub":
                if (cal.subtract(buffer, num) % 1 == 0) {
                    txtResult.setText((int) cal.subtract(buffer, num) + "");
                    isDecimal = false;
                } else {
                    txtResult.setText(cal.subtract(buffer, num) + "");
                    isDecimal = true;
                }
                break;
            default:
                if (num % 1 == 0) {
                    txtResult.setText((int) num + "");
                    isDecimal = false;
                } else {
                    isDecimal = true;
                }
        }
        defaultOperationBtnColor();
        operation = "none";
        isNewNum = true;
    }//GEN-LAST:event_btnResultActionPerformed

    void defaultOperationBtnColor() {
        btnDiv.setBackground(originColor);
        btnMul.setBackground(originColor);
        btnAdd.setBackground(originColor);
        btnSub.setBackground(originColor);
    }

    private void btnMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulActionPerformed
        // TODO add your handling code here:
        if (buffer != 0) {
            btnResultActionPerformed(null);
        }
        operation = "mul";
        buffer = Double.parseDouble(txtResult.getText());
        isNewNum = true;
        isDecimal = false;
        btnMul.setBackground(hover);
    }//GEN-LAST:event_btnMulActionPerformed

    private void btnSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubActionPerformed
        // TODO add your handling code here:
        if (buffer != 0) {
            btnResultActionPerformed(null);
        }
        operation = "sub";
        buffer = Double.parseDouble(txtResult.getText());
        isNewNum = true;
        isDecimal = false;
        btnSub.setBackground(hover);
    }//GEN-LAST:event_btnSubActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if (buffer != 0) {
            btnResultActionPerformed(null);
        }
        operation = "add";
        buffer = Double.parseDouble(txtResult.getText());
        isNewNum = true;
        isDecimal = false;
        btnAdd.setBackground(hover);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDivTo100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivTo100ActionPerformed
        // TODO add your handling code here:
        double tmp = Double.parseDouble(txtResult.getText());
        if (cal.divTo100(tmp) % 1 == 0) {
            txtResult.setText((int) cal.divTo100(tmp) + "");
        } else {
            DecimalFormat df = new DecimalFormat(getDF(cal.divTo100(tmp)));
            txtResult.setText(df.format(cal.divTo100(tmp)));
            isDecimal = true;
        }
        isNewNum = true;

    }//GEN-LAST:event_btnDivTo100ActionPerformed

    private void btnDivBy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivBy1ActionPerformed
        // TODO add your handling code here:
        double tmp = Double.parseDouble(txtResult.getText());
        if (cal.divByOne(tmp) % 1 == 0) {
            txtResult.setText((int) cal.divByOne(tmp) + "");
        } else {
            DecimalFormat df = new DecimalFormat(getDF(cal.divTo100(tmp)));
            txtResult.setText(df.format(cal.divByOne(tmp)));
            isDecimal = true;
        }
        isNewNum = true;
    }//GEN-LAST:event_btnDivBy1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Calculator().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnDivBy1;
    private javax.swing.JButton btnDivTo100;
    private javax.swing.JButton btnDot;
    private javax.swing.JButton btnMC;
    private javax.swing.JButton btnMR;
    private javax.swing.JButton btnMadd;
    private javax.swing.JButton btnMsub;
    private javax.swing.JButton btnMul;
    private javax.swing.JButton btnOpposite;
    private javax.swing.JButton btnResult;
    private javax.swing.JButton btnSqrt;
    private javax.swing.JButton btnSub;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables
}
