
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vu Quoc Hung
 */
public class mainFrame extends javax.swing.JFrame {
    //S0020 - 50
    /**
     * Creates new form mainFrame
     */
    JFileChooser fc;
    DefaultListModel<String> model;
    ArrayList<File> tmpList = new ArrayList<>();
    String spiltFileName[];
    
    
    public mainFrame() {
        initComponents();
        model = new DefaultListModel();
        listFile.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPath = new javax.swing.JTextField();
        btnList = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtField = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        listFile = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnList.setText("List File");
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        TxtField.setColumns(20);
        TxtField.setRows(5);
        jScrollPane2.setViewportView(TxtField);

        listFile.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listFileValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listFile);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPath, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnList, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnList)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
        TxtField.setText("");
        fc = new JFileChooser();        
        int r = fc.showOpenDialog(null);                
        FileInputStream fr=null;  
        BufferedReader br = null;
        if(r == JFileChooser.APPROVE_OPTION) {                                 
            File openF = fc.getSelectedFile();
            try {
                fr = new FileInputStream(openF);
                br = new BufferedReader(new InputStreamReader(fr));
                model.addElement(openF.getName());
                tmpList.add(openF);
                txtPath.setText(openF.getPath());  
                if(openF.toString().contains(".txt")) {
                    String s = "";
                    while (s != null) {
                    s = br.readLine();
                     if (s == null) {
                        break;
                        }
                    TxtField.append(s + "\n");
                
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Selected file is not a text file, content cannot be shown");
                }
            } catch (Exception e) {
               e.printStackTrace();
            }
        } else if(r == JFileChooser.CANCEL_OPTION){
           JOptionPane.showMessageDialog(null, "Open Failed");
        }
    }//GEN-LAST:event_btnListActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int idx = listFile.getSelectedIndex();
        File x = tmpList.get(idx);
        FileWriter fw = null;
        BufferedWriter bw = null; 
        try {
                fw = new FileWriter(x);
                bw = new BufferedWriter(fw);
                bw.write(TxtField.getText());
                bw.close();
                JOptionPane.showMessageDialog(null, "UPDATE SUCCESSFULLY");
            } catch (Exception e) {
                e.printStackTrace();
            }
        
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int idx = listFile.getSelectedIndex();
        model.remove(idx);
        tmpList.remove(idx);        
        JOptionPane.showMessageDialog(null, "DELETE SUCCESSFULLY");
        TxtField.setText("");
       
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void listFileValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listFileValueChanged
        int idx = 0;
        TxtField.setText("");
        FileInputStream fr=null;  
        BufferedReader br = null;
        idx = listFile.getSelectedIndex();
        if(idx == -1) {
            idx = 0;
        }
        File tmp = tmpList.get(idx);
        try {
                fr = new FileInputStream(tmp);
                br = new BufferedReader(new InputStreamReader(fr));
                txtPath.setText(tmp.getPath());
                if(tmp.toString().contains(".txt")) {
                    String s = "";
                    while (s != null) {
                    s = br.readLine();
                     if (s == null) {
                        break;
                    }
                    TxtField.append(s + "\n");
                
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Selected file is not a text file, content cannot be shown");
                }
           } catch (Exception e) {
               e.printStackTrace();
           }
    }//GEN-LAST:event_listFileValueChanged

        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TxtField;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnList;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listFile;
    private javax.swing.JTextField txtPath;
    // End of variables declaration//GEN-END:variables
}
