/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doing.l.p0002;

import java.util.HashMap;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author DoanNC
 */
public class Program extends javax.swing.JFrame {

    /**
     * Creates new form Program
     */
    private User user;
    boolean isVietnamese;
    ResourceBundle bundle;

    public Program() {
        initComponents();
        HashMap<String, Object> config = Weapon.loadConfig("lp0002-config.txt");
        isVietnamese = (boolean) config.get("lang");
    }

    public Program(User user) {
        initComponents();
        this.user = user;
        HashMap<String, Object> config = Weapon.loadConfig("lp0002-config.txt");
        isVietnamese = (boolean) config.get("lang");
        checkRole();
    }

    void loadLanguage(boolean isVietnamese) {
        if (isVietnamese) {
            Locale.setDefault(new Locale("vi", "VN"));
            bundle = ResourceBundle.getBundle("l.p0002.MessageBundle");
        } else {
            bundle = ResourceBundle.getBundle("l.p0002.MessageBundle", Locale.US);
        }
        lblTitle.setText(bundle.getString("main-management"));
        btnUserManagement.setText(bundle.getString("main-um"));
        btnProductManagement.setText(bundle.getString("main-pm"));
        btnPCM.setText(bundle.getString("main-pcm"));
        btnInventoryManagement.setText(bundle.getString("main-im"));
        btnBill.setText(bundle.getString("main-billing"));
        btnReport.setText(bundle.getString("main-reporting"));
        btnSupport.setText(bundle.getString("main-support"));
    }

    void checkRole() {
        String role = user.getRole();
//        String role = "Staff";
//        JOptionPane.showMessageDialog(this, role);
        switch (role) {
            case "Admin":
                //is Admin => Use method 1,2,4,6,7 => UM, PM, PCM, Reporting, Support
                btnInventoryManagement.setEnabled(false);
                btnBill.setEnabled(false);
                break;
            case "Staff":
                //is an Inventory Staff => Iventory Management
                btnProductManagement.setEnabled(false);
                btnPCM.setEnabled(false);
                btnBill.setEnabled(false);
                btnReport.setEnabled(false);
                btnSupport.setEnabled(false);
                break;
            default:
                //is Seller => Billing
                btnProductManagement.setEnabled(false);
                btnInventoryManagement.setEnabled(false);
                btnPCM.setEnabled(false);
                btnReport.setEnabled(false);
                btnSupport.setEnabled(false);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnUserManagement = new javax.swing.JButton();
        btnProductManagement = new javax.swing.JButton();
        btnInventoryManagement = new javax.swing.JButton();
        btnPCM = new javax.swing.JButton();
        btnBill = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        btnSupport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("MiniMart Management");

        btnUserManagement.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnUserManagement.setText("User Management");
        btnUserManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserManagementActionPerformed(evt);
            }
        });

        btnProductManagement.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnProductManagement.setText("Product Management");
        btnProductManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductManagementActionPerformed(evt);
            }
        });

        btnInventoryManagement.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnInventoryManagement.setText("Inventory Management");
        btnInventoryManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventoryManagementActionPerformed(evt);
            }
        });

        btnPCM.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnPCM.setText("Product Category Management ");
        btnPCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPCMActionPerformed(evt);
            }
        });

        btnBill.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnBill.setText("Billing");
        btnBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillActionPerformed(evt);
            }
        });

        btnReport.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnReport.setText("Reporting");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        btnSupport.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnSupport.setText("Support");
        btnSupport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                    .addComponent(btnUserManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProductManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInventoryManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPCM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSupport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblTitle)
                .addGap(28, 28, 28)
                .addComponent(btnUserManagement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProductManagement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInventoryManagement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPCM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBill)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSupport)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserManagementActionPerformed
        // TODO add your handling code here:
        this.dispose();
        UserManagement um = new UserManagement(user);
        um.setVisible(true);
    }//GEN-LAST:event_btnUserManagementActionPerformed

    private void btnProductManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductManagementActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ProductManagement pm = new ProductManagement(user);
        pm.setVisible(true);
    }//GEN-LAST:event_btnProductManagementActionPerformed

    private void btnInventoryManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryManagementActionPerformed
        // TODO add your handling code here:
        this.dispose();
        InventoryManagement im = new InventoryManagement(user);
        im.setVisible(true);
    }//GEN-LAST:event_btnInventoryManagementActionPerformed

    private void btnPCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPCMActionPerformed
        // TODO add your handling code here:
        this.dispose();
        PCM pcm = new PCM(user);
        pcm.setVisible(true);
    }//GEN-LAST:event_btnPCMActionPerformed

    private void btnBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillActionPerformed
        // TODO add your handling code here:
        //Not understand yet
        this.dispose();
    }//GEN-LAST:event_btnBillActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        //Not understand yet
        this.dispose();
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnSupportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupportActionPerformed
        // TODO add your handling code here:
        //Not understand yet
        this.dispose();
    }//GEN-LAST:event_btnSupportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Program().setVisible(true)
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBill;
    private javax.swing.JButton btnInventoryManagement;
    private javax.swing.JButton btnPCM;
    private javax.swing.JButton btnProductManagement;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnSupport;
    private javax.swing.JButton btnUserManagement;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
