/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package j2.s.p0126;

import java.awt.Color;

/**
 *
 * @author kim ngân
 */
public class JSP0126 extends javax.swing.JFrame {

    /**
     * Creates new form JSP126
     */
    public JSP0126() {
        initComponents();
        txt1.setForeground(Color.WHITE);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        txt1 = new javax.swing.JTextField();
        rdRed = new javax.swing.JRadioButton();
        rdBlue = new javax.swing.JRadioButton();
        rdGreen = new javax.swing.JRadioButton();
        rdBlack = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rdRed.setText("Red");
        rdRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdRedActionPerformed(evt);
            }
        });

        rdBlue.setText("Blue");
        rdBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBlueActionPerformed(evt);
            }
        });

        rdGreen.setText("Green");
        rdGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdGreenActionPerformed(evt);
            }
        });

        rdBlack.setText("Black");
        rdBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBlackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdBlue)
                    .addComponent(rdGreen)
                    .addComponent(rdBlack)
                    .addComponent(rdRed))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(rdRed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdBlue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdGreen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdBlack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdRedActionPerformed
        // TODO add your handling code here:
        rdRed.setSelected(true);
        rdBlack.setSelected(false);
        rdBlue.setSelected(false);
        rdGreen.setSelected(false);
        txt1.setText("Red is selected");
        txt1.setBackground(Color.RED);
    }//GEN-LAST:event_rdRedActionPerformed

    private void rdBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBlueActionPerformed
        // TODO add your handling code here:
        rdRed.setSelected(false);
        rdBlack.setSelected(false);
        rdBlue.setSelected(true);
        rdGreen.setSelected(false);
        txt1.setText("Blue is selected");
        txt1.setBackground(Color.BLUE);
        
    }//GEN-LAST:event_rdBlueActionPerformed

    private void rdGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdGreenActionPerformed
        // TODO add your handling code here:
        rdRed.setSelected(false);
        rdBlack.setSelected(false);
        rdBlue.setSelected(false);
        rdGreen.setSelected(true);
        txt1.setText("Green is selected");
        txt1.setBackground(Color.GREEN);
    }//GEN-LAST:event_rdGreenActionPerformed

    private void rdBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBlackActionPerformed
        // TODO add your handling code here:
        rdRed.setSelected(false);
        rdBlack.setSelected(true);
        rdBlue.setSelected(false);
        rdGreen.setSelected(false);
        txt1.setText("Black is selected");
        txt1.setBackground(Color.BLACK);
    }//GEN-LAST:event_rdBlackActionPerformed

    /**
     * @param args the command line arguments
     * rdRed.setSelected(false);
        rdBlack.setSelected(false);
        rdBlue.setSelected(true);
        rdGreen.setSelected(false);
        txt1.setText("Blue is selected");
        txt1.setBackground(Color.BLUE);
        
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        rdRed.setSelected(false);
//        rdBlack.setSelected(false);
//        rdBlue.setSelected(true);
//        rdGreen.setSelected(false);
//        txt1.setText("Blue is selected");
//        txt1.setBackground(Color.BLUE);
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JSP0126.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JSP0126.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JSP0126.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JSP0126.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JSP0126().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton rdBlack;
    private javax.swing.JRadioButton rdBlue;
    private javax.swing.JRadioButton rdGreen;
    private javax.swing.JRadioButton rdRed;
    private javax.swing.JTextField txt1;
    // End of variables declaration//GEN-END:variables
}
