/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phucldh.ui;

import java.sql.SQLException;
import java.text.ParseException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.ir.BreakNode;
import phucldh.daos.CourseDAO;
import phucldh.dtos.CourseDTO;

/**
 *
 * @author DELL
 */
public class CoursesManagement extends javax.swing.JFrame {

    private Vector<CourseDTO> list = null;

    public int findByCode(String code) {
        if (list == null) {
            return -1;
        }
        for (int i = 0; i < list.size(); i++) {
            if (list.get(i).getCode().equals(code)) {
                return i;
            }
        }
        return -1;
    }

    public void loadData() {
        CourseDAO courseDAO = new CourseDAO();
        try {
            list = courseDAO.getListCourse();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public void clearText() {
        txtNewCode.setText("");
        txtNewName.setText("");
        txtNewPrice.setText("");
    }

    public CoursesManagement() {
        initComponents();
        loadData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmAddNew = new javax.swing.JFrame();
        lbNewCode = new javax.swing.JLabel();
        lbNewName = new javax.swing.JLabel();
        lbNewPrice = new javax.swing.JLabel();
        txtNewCode = new javax.swing.JTextField();
        txtNewName = new javax.swing.JTextField();
        txtNewPrice = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        frmDisplay = new javax.swing.JFrame();
        lbListAllTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDisplayAll = new javax.swing.JTextArea();
        frmSearch = new javax.swing.JFrame();
        lbSearchCode = new javax.swing.JLabel();
        lbSearchCourseName = new javax.swing.JLabel();
        lbSearchCredit = new javax.swing.JLabel();
        txtSearchCode = new javax.swing.JTextField();
        btnSearchCourse = new javax.swing.JButton();
        txtSearchCourseName = new javax.swing.JTextField();
        txtSearchPrice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnWindowAdd = new javax.swing.JButton();
        btnWindowDisplayAll = new javax.swing.JButton();
        btnWindowSearch = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        frmAddNew.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        frmAddNew.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                frmAddNewWindowClosing(evt);
            }
        });

        lbNewCode.setText("Code");
        lbNewCode.setMaximumSize(new java.awt.Dimension(35, 20));
        lbNewCode.setMinimumSize(new java.awt.Dimension(35, 20));
        lbNewCode.setPreferredSize(new java.awt.Dimension(35, 20));

        lbNewName.setText("Name");
        lbNewName.setPreferredSize(new java.awt.Dimension(35, 20));

        lbNewPrice.setText("Price");
        lbNewPrice.setPreferredSize(new java.awt.Dimension(35, 20));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmAddNewLayout = new javax.swing.GroupLayout(frmAddNew.getContentPane());
        frmAddNew.getContentPane().setLayout(frmAddNewLayout);
        frmAddNewLayout.setHorizontalGroup(
            frmAddNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmAddNewLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClear)
                .addGap(81, 81, 81))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmAddNewLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(frmAddNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbNewPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbNewName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNewCode, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(frmAddNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNewName, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNewPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNewCode, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        frmAddNewLayout.setVerticalGroup(
            frmAddNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmAddNewLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(frmAddNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbNewCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNewCode, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frmAddNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNewName, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(lbNewName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frmAddNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNewPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNewPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(frmAddNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        frmDisplay.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                frmDisplayWindowClosing(evt);
            }
        });

        lbListAllTitle.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lbListAllTitle.setText("List of all Courses (Order by Credit)");

        txtDisplayAll.setColumns(20);
        txtDisplayAll.setRows(5);
        jScrollPane1.setViewportView(txtDisplayAll);

        javax.swing.GroupLayout frmDisplayLayout = new javax.swing.GroupLayout(frmDisplay.getContentPane());
        frmDisplay.getContentPane().setLayout(frmDisplayLayout);
        frmDisplayLayout.setHorizontalGroup(
            frmDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(frmDisplayLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(lbListAllTitle)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        frmDisplayLayout.setVerticalGroup(
            frmDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbListAllTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addContainerGap())
        );

        frmSearch.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                frmSearchWindowClosing(evt);
            }
        });

        lbSearchCode.setText("Enter Code:");

        lbSearchCourseName.setText("Course Name:");

        lbSearchCredit.setText("Price:");

        btnSearchCourse.setText("Search");
        btnSearchCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmSearchLayout = new javax.swing.GroupLayout(frmSearch.getContentPane());
        frmSearch.getContentPane().setLayout(frmSearchLayout);
        frmSearchLayout.setHorizontalGroup(
            frmSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmSearchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(frmSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbSearchCourseName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(lbSearchCode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbSearchCredit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(frmSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmSearchLayout.createSequentialGroup()
                        .addComponent(txtSearchCode, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSearchCourse)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(frmSearchLayout.createSequentialGroup()
                        .addComponent(txtSearchCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(frmSearchLayout.createSequentialGroup()
                        .addComponent(txtSearchPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        frmSearchLayout.setVerticalGroup(
            frmSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmSearchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(frmSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmSearchLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbSearchCode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSearchCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchCode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(frmSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSearchCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(frmSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSearchCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel1.setText("Courses Magement");

        btnWindowAdd.setText("Add New Course");
        btnWindowAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWindowAddActionPerformed(evt);
            }
        });

        btnWindowDisplayAll.setText("Display All Courses");
        btnWindowDisplayAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWindowDisplayAllActionPerformed(evt);
            }
        });

        btnWindowSearch.setText("Search Course By Course Code");
        btnWindowSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWindowSearchActionPerformed(evt);
            }
        });

        btnExit.setText("Exit Application");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnWindowDisplayAll, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnWindowAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnWindowSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnWindowAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnWindowDisplayAll, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnWindowSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnWindowAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWindowAddActionPerformed
        frmAddNew.setSize(405, 270);
        frmAddNew.setVisible(true);
        clearText();

    }//GEN-LAST:event_btnWindowAddActionPerformed

    private void btnWindowDisplayAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWindowDisplayAllActionPerformed
        txtDisplayAll.setText("");
        if (list.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Empty Course!");
            return;
        }
        frmDisplay.setSize(510, 360);
        frmDisplay.setVisible(true);
        for (CourseDTO courseDTO : list) {
            txtDisplayAll.append(courseDTO.getCode() + "     |     " + courseDTO.getName() + "    |     " + courseDTO.getPrice() + "\n");
        }
    }//GEN-LAST:event_btnWindowDisplayAllActionPerformed

    private void btnWindowSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWindowSearchActionPerformed
        if (list.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Empty course!");
            return;
        }
        frmSearch.setSize(370, 180);
        frmSearch.setVisible(true);
    }//GEN-LAST:event_btnWindowSearchActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String strCode = txtNewCode.getText().trim();
        String strName = txtNewName.getText().trim();
        String strPrice = txtNewPrice.getText().trim();
        int price = 0;
        // check code
        if (strCode.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Code is not empty!");
            txtNewCode.requestFocus();
            return;
        }
        try {
            if (strCode.matches("e\\d{2}") == false) {
                JOptionPane.showMessageDialog(this, "Code is matches:  'e**'");
                txtNewCode.requestFocus();
                return;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        if (list != null) {
            for (int i = 0; i < list.size(); i++) {
                if (strCode.equals(list.get(i).getCode().trim())) {
                    JOptionPane.showMessageDialog(this, "Duplicate code!");
                    return;
                }
            }
        }
        

        // check name 
        if (strName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name is not empty!");
            return;
        }

        // check price 
        if (strPrice.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Price is not empty!");
            return;
        }
        try {
            price = Integer.parseInt(strPrice);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Price is a number!");
            return;
        }
        if (price <= 0) {
            JOptionPane.showMessageDialog(this, "Price is positive number!");
            return;
        }
        boolean result = false;
        CourseDAO courseDAO = new CourseDAO();
        CourseDTO courseDTO = new CourseDTO(strCode, strName, price);

        try {
            courseDAO.insertCourse(courseDTO);
            result = true;
        } catch (Exception e) {
            e.printStackTrace();
        }

        if (result = true) {
            loadData();
            JOptionPane.showMessageDialog(this, "Add Course successfully!");
            clearText();

        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearText();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSearchCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCourseActionPerformed
        // TODO add your handling code here:
        String code = txtSearchCode.getText().trim();
        if (code.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill code!");
            return;
        }

        int pos = findByCode(code);
        if (pos > -1) {
            txtSearchCourseName.setText(list.get(pos).getName());
            txtSearchPrice.setText(Integer.toString(list.get(pos).getPrice()));
            txtSearchCourseName.enable(false);
            txtSearchPrice.enable(false);
        } else {
            JOptionPane.showMessageDialog(this, "Course does not exist!");
        }

    }//GEN-LAST:event_btnSearchCourseActionPerformed

    private void frmAddNewWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_frmAddNewWindowClosing
        frmAddNew.dispose();
    }//GEN-LAST:event_frmAddNewWindowClosing

    private void frmDisplayWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_frmDisplayWindowClosing
        frmDisplay.dispose();
    }//GEN-LAST:event_frmDisplayWindowClosing

    private void frmSearchWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_frmSearchWindowClosing
        frmSearch.dispose();
    }//GEN-LAST:event_frmSearchWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoursesManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoursesManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoursesManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoursesManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoursesManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSearchCourse;
    private javax.swing.JButton btnWindowAdd;
    private javax.swing.JButton btnWindowDisplayAll;
    private javax.swing.JButton btnWindowSearch;
    private javax.swing.JFrame frmAddNew;
    private javax.swing.JFrame frmDisplay;
    private javax.swing.JFrame frmSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbListAllTitle;
    private javax.swing.JLabel lbNewCode;
    private javax.swing.JLabel lbNewName;
    private javax.swing.JLabel lbNewPrice;
    private javax.swing.JLabel lbSearchCode;
    private javax.swing.JLabel lbSearchCourseName;
    private javax.swing.JLabel lbSearchCredit;
    private javax.swing.JTextArea txtDisplayAll;
    private javax.swing.JTextField txtNewCode;
    private javax.swing.JTextField txtNewName;
    private javax.swing.JTextField txtNewPrice;
    private javax.swing.JTextField txtSearchCode;
    private javax.swing.JTextField txtSearchCourseName;
    private javax.swing.JTextField txtSearchPrice;
    // End of variables declaration//GEN-END:variables

}
